version: "3"
services:
  web:
    build: "./web"
    image: web:latest
    container_name: web
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./web/html:/usr/share/nginx/html
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
  api:
    build: "./api"
    image: api:latest
    container_name: api
    ports:
      - "3000:3000"
